### ISSUE TITLE
Provide standard deviation for reference samples?

### ISSUE THREAD

**Issue by drussellmrichie** [milesgranger/gap_statistic#18]
Hi,

Thanks for providing this nice tool! It's very easy to plug into my work. :-)

I was wondering if you'd thought about, instead of just returning the gap statistic for each value of k, returning the value s_k for the reference distribution as well, so we can easily do the Tibshirani-recommended approach: choose the smallest k such that Gap(k) > Gap(k+1) - s(k+1).

https://datasciencelab.wordpress.com/2013/12/27/finding-the-k-in-k-means-clustering/

Thanks again for writing this package!

Russell

**Comment by milesgranger** [comment]
Hello!

Great idea! Should be pretty easy to include that. Hard to provide a timeline of when I'll have this in, but I'll start working on it soon. Thanks for the suggestions and link! :smiley:

**Comment by dvukolov** [comment]
Please forgive me for writing under a closed issue. I had a similar question: wanted to plot the error bars around the Gap statistic to replicate the canonical plots. It seems that the "sk" and the "sk*" columns are dropped from the resulting gap_df DataFrame. One could potentially reconstruct them from the "diff" columns, but without the very first entry due to a .shift() function call. Would it be possible to return "sk" and "sk*" as part of gap_df? Please correct me if I'm missing some other possibility for plotting the error bars. Thank you!

**Comment by milesgranger** [comment]
No problem!

I don't see why keeping them would present any issue. Just with the rust issue, I doubt I can do anything productive here until next week maybe. How do you feel about making a PR for this?

**Comment by dvukolov** [comment]
Thank you for your offer! I will do it shortly.
