### ISSUE TITLE
Optimal # of Clusters changes every run

### ISSUE THREAD

**Issue by supersaiyanesee** [milesgranger/gap_statistic#36]
I tried implementing your code for a research paper, I just followed your example from the uploaded notebook.
I have an issue regarding the optimal number of clusters as it changes every run using the same dataset. 
Do I need to optimize something?

**Comment by milesgranger** [comment]
Difficult to debug things like this due to the random initialization of the centroids. In tests the datasets are quite clearly clustered which leads to much more predictable values for N clusters.

If your dataset is not well clustered it, especially in higher dimensions, it may be quite normal for different values to be produced.

**Comment by hrsma2i** [comment]
@supersaiyanesee 
I can fix the seed like:

```py
from scipy.cluster.vq import kmeans2

optimalK = OptimalK(
    ...
    # https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.vq.kmeans2.html
    clusterer=kmeans2,
    clusterer_kwargs={"seed": YOUR_SEED},
)
```

You must use **SciPy>=1.7.0** .
